### ISSUE TITLE
checkpoint设置问题

### ISSUE THREAD

**Issue by XiaoyuZhuang** [friedrichor/Text-to-Image-Summary#1]
你好，请问checkpoint点如何设，训练好的模型默认保存在 txt2img-finetune-lora/pytorch_lora_weights.bin，但我没有找到这个文件，整个工作站都没有。还有model_path = "/datas/kfh/finetune_sd/text2image/txt2img-finetune-lora/checkpoint-500/pytorch_model.bin"，这个pytorch_model.bin是在huggingface中吗？本地我找到了这个文件，但有若干个，是要Unet文件夹里面的吗。谢谢！

**Comment by XiaoyuZhuang** [comment]
我好像大概懂了，我阅读了官方的说明文件，说需要先训练模型，也就是在cmd中运行sh，才会生成bin文件，不知道我理解的对不对

**Comment by friedrichor** [comment]
是的，要先训练模型，model_path 是训练后本地保存模型的位置

**Comment by XiaoyuZhuang** [comment]
好的，谢谢大佬 [thanks.png]
