### ISSUE TITLE
train_text_to_image_lora.sh 运行问题

### ISSUE THREAD

**Issue by XiaoyuZhuang** [friedrichor/Text-to-Image-Summary#2]
你好
我在生成bin文件时，遇到问题。通过git bash运行代码sh train_text_to_image_lora.sh时，遇到报错，见附件error_log。
我查阅了很多解决方案，但不能解决问题。请问如何解决该问题？
我的平台是windows 11，而不是linux。是否应该在linux平台上运行该代码？
谢谢！
[error_log.txt](https://github.com/friedrichor/Text-to-Image-Summary/files/11361385/error_log.txt)

**Comment by friedrichor** [comment]
运行sh文件肯定是linux系统运行更好，在windows运行sh文件应该可以通过Git Bash来运行。或者就是把sh文件中的相关参数设置在.py文件中的parse_args函数中更改（改default的值），不过这样的话如何使用accelerate我并不了解。

**Comment by XiaoyuZhuang** [comment]
问题解决，核心在于其中一个包 bitsandbytes 不支持windows平台。解决办法可以参见 bitsandbytes 的讨论区
